@startuml Classes Diagram 
Title Classes Architecture

class Caretaker {
  name: String
  email: String
  city: String
  creationDate : Date
  photo : String
  description : String
  links : Array
  socials : Array
  acceptsVolunteers : Boolean
  acceptsDonations : Boolean

  animals : [Animal]
  posts : [Post]

  constructor(name: String, email: String, city: String)
  addAnimal(animal: Animal)
  addPost(post: Post)
}

class Post {
  title: String
  photo: String
  content: String
  tags: Array
  creationDate: Date
  animals: [Animal]
    
  constructor(title: String)
}

class Animal {
  name: String
  photo: String
  description: String
  isAdoptable: Boolean
  isAdopted : Boolean
  
  constructor(name: String)
    
}

Caretaker "1" o--> "0..*" Animal : cares for
Caretaker "1" o--> "0..*" Post : created
Post "1" o--> "0..*" Animal : includes
Animal "1" o--> "0..*" Post : appears on
@enduml