version: '3.4'

services:
  app:
    image: codename-paws
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
