version: '3.4'

services:
  app:
    image: codename-paws
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo/codename-paws
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    logging:
      driver: none
    ports:
      - 27017:27017
