@startuml Classes Diagram 
Title Use-cases

left to right direction
skinparam Monochrome true
skinparam BackgroundColor LightGray
skinparam ClassBackgroundColor GhostWhite
skinparam ClassBorderColor DimGray
skinparam ClassFontSize 16
skinparam ClassFontStyle bold
skinparam ClassBorderThickness 0
skinparam ClassHeaderBackgroundColor midnightblue
skinparam ClassFontColor ghostwhite
skinparam ArrowColor black
skinparam ArrowThickness 2
skinparam roundCorner 16
skinparam Shadowing true
skinparam Padding 2

actor "Shelter" as Shelter 
package Content_actions {
  usecase "Add animal" as addAnimal
  usecase "Add post" as addPost
}
actor "Visitor" as visitor

package App_Content {
  usecase "Animals" as animals
  usecase "Posts" as posts
}

Shelter --> addAnimal
Content_actions --> App_Content
Shelter --> addPost
visitor --> animals
visitor --> posts
@enduml 